### ISSUE TITLE
Incorrect line breaks on multi-code point emoji

### ISSUE THREAD

**Issue by jeremysf** [niklasvh/css-line-break#2]
First off, thank you for this great library! On the issue: for example, the 👨‍👩‍👧‍👦emoji, which is represented by a sequence the four emoji code points and zero width joiners result in breaks for each of the emoji code points.

**Comment by niklasvh** [comment]
Thanks for reporting this! I'll need to investigate this further

**Comment by be5invis** [comment]
There are regexes that could recognize Emoji:
 * http://unicode.org/reports/tr51/#EBNF_and_Regex
 * https://github.com/mathiasbynens/emoji-regex

**Comment by alexsorokoletov** [comment]
@niklasvh this issue also affects html2canvas - rendering multipoint emojis is broken

**Comment by niklasvh** [comment]
Little late to the party, but this was fixed in #2 (see https://jsfiddle.net/w6romb5n/1/)

**Comment by alexsorokoletov** [comment]
Thank you!

**Comment by shuding** [comment]
I don't think this is fully fixed, taking the `🏳️‍🌈` emoji as an example:

<img width="381" alt="CleanShot 2022-02-06 at 21 43 48@2x" src="https://user-images.githubusercontent.com/3676859/152700559-5758f1b1-9c72-4da6-9a8f-041f479ed799.png">
