### ISSUE TITLE
Build breaks in IE11 view16.slice

### ISSUE THREAD

**Issue by SoroTrestal** [niklasvh/css-line-break#4]
Hello, my build breaks in IE11 saying slice is undefined.

````
var createTrieFromBase64 = exports.createTrieFromBase64 = function createTrieFromBase64(base64) {
    var buffer = (0, _Util.decode)(base64);
    var view32 = Array.isArray(buffer) ? (0, _Util.polyUint32Array)(buffer) : new Uint32Array(buffer);
    var view16 = Array.isArray(buffer) ? (0, _Util.polyUint16Array)(buffer) : new Uint16Array(buffer);
    var headerLength = 24;

    var index = **view16.slice(headerLength / 2, view32[4] / 2);**
    var data = view32[5] === 2 ? view16.slice((headerLength + view32[4]) / 2) : **view32.slice(Math.ceil((headerLength + view32[4]) / 4));**

    return new Trie(view32[0], view32[1], view32[2], view32[3], index, data);
};
````

Regards

**Comment by leiyaguang** [comment]
The same problem.

**Comment by MuthuD** [comment]
I'm facing this same problem, with Angular 6 and IE11.
Anyone have a solution, Any suggestions would be appreciated.

Thank you,
Muthu D

**Comment by naizut** [comment]
The same problem. I had to catch the error and turned the object  to array.
 `    try{
        var index = view16.slice(headerLength / 2, view32[4] / 2);
        var data = view32[5] === 2 ? view16.slice((headerLength + view32[4]) / 2) : view32.slice(Math.ceil((headerLength + view32[4]) / 4));
        console.log("tried:"+index)
    }catch(e){
        // console.log(e)
        var arr = [];
        for (var key in view16){
            arr[key] = view16[key];
        }
        var arr1 = [];
        for (var key in view32){
            arr1[key] = view32[key];
        }
        var index = arr.slice(headerLength / 2, view32[4] / 2);
        var data = [5] === 2 ? arr.slice((headerLength + view32[4]) / 2) : arr1.slice(Math.ceil((headerLength + view32[4]) / 4));
        console.log("catched:"+index)
        console.log("catched:"+data)
    }`
got different result. Any other solution?

**Comment by niklasvh** [comment]
fixed with https://github.com/niklasvh/css-line-break/commit/3f503fb5798f0ef686156574d807675cb465b2d4
